name: Daily Madrid Courses Scrape

on:
  schedule:
    - cron: "5 3 * * *"   # daily at 03:05 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright pandas openpyxl
          playwright install --with-deps chromium

      - name: Run scraper
        run: |
          python scraper/scrape_madrid.py

      - name: Show outputs
        if: always()
        run: |
          echo "==== repo root ===="
          ls -la
          echo "==== public ===="
          ls -la public || true
          echo "==== debug ===="
          ls -la debug || true
          [ -f public/madrid_cursos.json ] && wc -c public/madrid_cursos.json || echo "NO JSON"
          [ -f public/madrid_cursos.xlsx ] && wc -c public/madrid_cursos.xlsx || echo "NO XLSX"

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: madrid-cursos-output
          path: |
            public/madrid_cursos.json
            public/madrid_cursos.xlsx
            debug/**/*.png
            debug/**/*.html
          if-no-files-found: warn

      - name: Commit & push artifacts
        run: |
          set -e
          if [ ! -f public/madrid_cursos.xlsx ] || [ ! -f public/madrid_cursos.json ]; then
            echo "❌ Missing outputs, not committing."
            exit 1
          fi
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update madrid cursos feed"
            git push
          fi
