name: Daily Madrid Courses Scrape

on:
  schedule:
    - cron: "5 3 * * *"   # daily at 03:05 UTC
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright pandas openpyxl
          playwright install --with-deps chromium

      - name: Run scraper
        run: python scraper/scrape_madrid.py

      - name: Commit & push artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add public/madrid_cursos.xlsx public/madrid_cursos.json
          git diff --quiet && echo "No changes" || (git commit -m "chore: update madrid cursos feed" && git push)
